rest-api-key: ${RESTAPI_KEY}
redirect-uri: "http://localhost:8080/OauthCodeResPage"
client-secret: ""
authorize-uri: "https://kauth.kakao.com/oauth/authorize"
token-uri: "https://kauth.kakao.com/oauth/token"
kakao-api-host: "https://kapi.kakao.com"

server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
    session:
      cookie:
        http-only: true
        same-site: none

  port: 80

spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
